kind: Service
apiVersion: v1
metadata:
  name: home-exercise
spec:
  type: NodePort
  selector:
    app: home-exercise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080